// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1;
using WebApplication1.Repository;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MyMegaBotContext))]
    partial class MyMegaBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.CommandEntity", b =>
                {
                    b.Property<int>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandTrigger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsScript")
                        .HasColumnType("bit");

                    b.Property<string>("ScriptName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceNames")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommandId");

                    b.ToTable("CommandEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
